# Generated by Django 5.2.1 on 2025-07-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_store_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(default='khartoum/om dorman', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
