# Generated by Django 5.2.1 on 2025-06-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='context_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
