# Generated by Django 5.2.1 on 2025-06-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_emailtemplate_context_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='context_fields',
        ),
    ]
