# Generated by Django 5.2.1 on 2025-07-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accountType',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer')], default='buyer', help_text="Type of account: 'seller' or 'buyer'.", max_length=10),
        ),
    ]
