# Generated by Django 5.2.1 on 2025-07-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_accounttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='accountType',
            new_name='account_type',
        ),
    ]
