# Generated by Django 5.2.1 on 2025-07-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_created_at_user_updated_at'),
        ('products', '0007_producthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_products',
            field=models.ManyToManyField(blank=True, related_name='favourited_by', to='products.product'),
        ),
    ]
