# Generated by Django 5.2.1 on 2025-07-30 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'carts_cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('size', models.CharField(blank=True, help_text='Size variation for products that have sizes', max_length=50, null=True)),
                ('product_properties', models.JSONField(blank=True, help_text='Additional product properties like color, etc.', null=True)),
                ('is_stock_reserved', models.BooleanField(default=False, help_text='Whether stock is currently reserved for this cart item')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carts.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'carts_cart_item',
                'indexes': [models.Index(fields=['cart', 'product'], name='carts_cart__cart_id_5f4f72_idx'), models.Index(fields=['added_at'], name='carts_cart__added_a_63b57b_idx'), models.Index(fields=['is_stock_reserved'], name='carts_cart__is_stoc_ba5875_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('size__isnull', False)), fields=('cart', 'product', 'size'), name='unique_cart_product_size'), models.UniqueConstraint(condition=models.Q(('size__isnull', True)), fields=('cart', 'product'), name='unique_cart_product_no_size')],
            },
        ),
    ]
