# Generated by Django 5.2.1 on 2025-07-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='unit_price_at_time',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Unit price when item was added to cart', max_digits=10),
        ),
    ]
