# Generated by Django 5.2.1 on 2025-07-31 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producthistory',
            old_name='price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='producthistory',
            old_name='recorded_at',
            new_name='snapshot_taken_at',
        ),
    ]
