# Generated by Django 5.2.1 on 2025-07-28 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_updated_at_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('has_sizes', models.BooleanField(default=False)),
                ('sizes', models.JSONField(blank=True, null=True)),
                ('owner_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(max_length=100)),
                ('properties', models.JSONField(blank=True, null=True)),
                ('picture', models.ImageField(upload_to='history/products/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('store_location', models.CharField(blank=True, max_length=255, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='products.product')),
            ],
        ),
    ]
