# Generated by Django 5.2.1 on 2025-07-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_producthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
