# Generated by Django 5.2.1 on 2025-07-30 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('on_cart', 'On Cart'), ('under_paying', 'Under Paying'), ('pending', 'Pending'), ('on_process', 'On Process'), ('on_shipping', 'On Shipping'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='on_cart', max_length=20)),
                ('product_variation', models.JSONField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_name_at_order', models.CharField(blank=True, max_length=255)),
                ('product_price_at_order', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_address', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('after_delivery', 'Cash on Delivery'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money')], default='credit_card', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('payment_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_key', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_expires_at', models.DateTimeField(blank=True, help_text='Payment deadline for under_paying orders', null=True)),
                ('customer_notes', models.TextField(blank=True, help_text='Customer order notes')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('payment_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='payments.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.product')),
                ('product_history', models.ForeignKey(blank=True, help_text='Snapshot of product state when order was created', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producthistory')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_id'], name='orders_orde_order_i_205064_idx'), models.Index(fields=['user_id', 'status'], name='orders_orde_user_id_dac4f5_idx'), models.Index(fields=['payment_status'], name='orders_orde_payment_bc131d_idx'), models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx')],
            },
        ),
    ]
