version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: builds/prod/Dockerfile
    command: >
     sh -c "
      ./wait-for-it.sh db:3306 --timeout=60 --strict &&
      ./wait-for-it.sh redis:6379 --timeout=60 --strict &&
      ./wait-for-it.sh elasticsearch:9200 --timeout=60 --strict &&
      find . -path '*/migrations/*.py' -not -name '__init__.py' -delete &&
      find . -path '*/migrations/*.pyc' -delete &&
      python manage.py makemigrations --noinput &&
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      chmod +x /api/start_celery.sh &&
      chmod +x /api/start_celerybeat.sh &&
      supervisord -c /etc/supervisor/conf.d/supervisord.conf
      "
    volumes:
      - static_volume:/api/staticfiles
      - media_volume:/api/media
    expose:
      - "8000"
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - sudamall-net

  db:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    env_file:
      - .env.prod
    volumes:
      - db_data:/var/lib/mysql
      - ./config/mysql.cnf:/etc/mysql/conf.d/custom.cnf
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sudamall-net

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379" # host:container
    volumes:
      - redis_data:/data
    networks:
      - sudamall-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - sudamall-net

volumes:
  static_volume:
  media_volume:
  redis_data:
  db_data:
  esdata:

networks:
  sudamall-net:
    external: true