name: Django CI/CD - Dev

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  development:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create .env files
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> api/.env
          echo "DEBUG=${{ secrets.DEBUG }}" >> api/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> api/.env
          echo "CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }}" >> api/.env
          echo "REDIS_DATABASE_URL=${{ secrets.REDIS_DATABASE_URL }}" >> api/.env
          echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> api/.env

          echo "DEBUG=${{ secrets.DEBUG }}" >> api/.env.dev
          echo "DJANGO_ENV=${{ secrets.DJANGO_ENV }}" >> api/.env.dev

      - name: Build Docker containers
        run: docker compose -f api/docker-compose.yml build

      - name: Start containers in background
        run: docker compose -f api/docker-compose.yml up -d

      - name: Wait for Redis
        run: |
          echo "Waiting for Redis to be ready..."
          for i in {1..10}; do
            docker exec $(docker ps -qf "name=redis") redis-cli ping && break
            sleep 2
          done

      - name: Apply Migrations
        run: |
          docker compose -f api/docker-compose.yml exec web python manage.py makemigrations
          docker compose -f api/docker-compose.yml exec web python manage.py migrate

      - name: Run Tests
        run: docker compose -f api/docker-compose.yml exec web python manage.py test

      - name: Tear Down
        run: docker compose -f api/docker-compose.yml down -v
