name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Build and start services
      run: |
        docker compose -f api/docker-compose.yml up -d --build

    - name: Wait for web to become healthy
      run: |
        for i in {1..20}; do
          if docker logs api-web-1 2>&1 | grep -q "Starting development server at"; then
            echo "Web is ready!"
            break
          fi
          echo "Waiting for web to start..."
          sleep 5
        done

    - name: Run Django tests
      run: docker exec api-web-1 python manage.py test
