name: Django CI/CD - Dev

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build Docker containers
        run: docker compose -f api/docker-compose.dev.yml

      - name: Wait for DB to be ready
        run: |
          docker compose -f docker-compose.dev.yml up -d
          sleep 10  # Optional: Replace with proper wait-for-it script

      - name: Apply Migrations
        run: docker compose -f docker-compose.dev.yml run --rm web python manage.py migrate

      - name: Run Tests
        run: docker compose -f docker-compose.dev.yml run --rm web python manage.py test

      - name: Tear Down
        run: docker compose -f docker-compose.dev.yml down -v