name: Django CI/CD - Dev

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Create .env file
        run: |
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> api/.env
          echo "DJANGO_DEBUG=${{ secrets.DEBUG }}" >> api/.env
          echo "DATABASE_URL=${{ secrets.ALLOWED_HOSTS }}" >> api/.env
          echo "DATABASE_URL=${{ secrets.REDAIS_DATABASE_URL }}" >> api/.env
          echo "DATABASE_URL=${{ secrets.CELERY_BROKER_URL }}" >> api/.env
      - name: Create .env.dev file
        run: |
          echo "DJANGO_SECRET_KEY=${{ secrets.DEBUG }}" >> api/.env.dev
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_ENV }}" >> api/.env.dev
      - name: Build Docker containers
        run: docker compose -f api/docker-compose.yml build

      - name: Wait for DB to be ready
        run: |
          docker compose -f api/docker-compose.yml build
          sleep 10  # Optional: Replace with proper wait-for-it script
    
      - name: Debug - List files
        run: |
          pwd
          ls -R

      - name: Apply Migrations
        run: |
         docker compose -f api/docker-compose.yml run --rm web python manage.py migrate

      - name: Run Tests
        run: |
          docker compose -f api/docker-compose.yml run --rm web python manage.py test

      - name: Tear Down
        run: |
          docker compose -f api/docker-compose.yml down -v
